package com.utn.dds.javaianos.parser;

/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SUMA = 6;
  /** RegularExpression Id. */
  int RESTA = 7;
  /** RegularExpression Id. */
  int MULTIPLICACION = 8;
  /** RegularExpression Id. */
  int DIVISION = 9;
  /** RegularExpression Id. */
  int PARENTESIS_IZQUIERDO = 10;
  /** RegularExpression Id. */
  int PARENTESIS_DERECHO = 11;
  /** RegularExpression Id. */
  int NUMERO = 12;
  /** RegularExpression Id. */
  int DIGITO = 13;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 14;
  /** RegularExpression Id. */
  int LETRA = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<NUMERO>",
    "<DIGITO>",
    "<IDENTIFICADOR>",
    "<LETRA>",
  };

}
